// <auto-generated />
using System;
using KozosKonyvtar.MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KozosKonyvtar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521043734_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KozosKonyvtar.MODEL.Helyszin", b =>
                {
                    b.Property<int>("HelyszinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HelyszinId"));

                    b.Property<string>("HelyszinNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HelyszinId");

                    b.ToTable("Helyszin");
                });

            modelBuilder.Entity("KozosKonyvtar.MODEL.Orszag", b =>
                {
                    b.Property<int>("OrszagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrszagId"));

                    b.Property<string>("OrszagKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrszagId");

                    b.ToTable("Orszag");
                });

            modelBuilder.Entity("KozosKonyvtar.MODEL.Sportolo", b =>
                {
                    b.Property<int>("SportoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportoloId"));

                    b.Property<int>("OrszagId")
                        .HasColumnType("int");

                    b.Property<string>("SportoloNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportoloId");

                    b.ToTable("Sportolo");
                });

            modelBuilder.Entity("KozosKonyvtar.MODEL.Verseny", b =>
                {
                    b.Property<int>("VersenyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersenyId"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<decimal>("Eredmeny")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Helyezes")
                        .HasColumnType("int");

                    b.Property<int>("HelyszinId")
                        .HasColumnType("int");

                    b.Property<int>("SportoloId")
                        .HasColumnType("int");

                    b.HasKey("VersenyId");

                    b.ToTable("Verseny");
                });
#pragma warning restore 612, 618
        }
    }
}
